### ISSUE TITLE
Implement button for improving unit strength

### ISSUE THREAD

**Issue by W01fw00d** [W01fw00d/barbarians#28]
Units with low strength are useless on the late game: lets implement a button on their info div that lets us improve them with gold. It would only improve the strenght of that unit, but it would be cheaper than the town quality improvement. Discussion open about other ways of leveling up weak units.

**Comment by MHase** [comment]
#42 PR created with my approach :)

**Comment by W01fw00d** [comment]
Nice, solved and close :)
